// to define a name for the compiler generated static class which contains all
// top level items, it has to be defined before package name using annotation JvmName
@file: JvmName("BikeStaticClass") // using this annotation we can define
// custom name to the static class which can be used by java code to refer this
// class top-level items

package javacode.interoperability.javacode.to.kotlincode

class Bike(val modelName: String, val makeName: String, val mileage: Int, val price: Int) {
    constructor(modelName: String, mileage: Int): this(modelName, "Honda", mileage, 58000) {

    }
}

fun bikeTopLevel() {
    println("this is Bike Top Level Function")
}

// this is extension function defined for String class in this file, this function can
// also be accessed using the static class instance generated by compiler for all
// top level items
fun String.printBikeName() {
    println(this)
}

fun main() {
    "Printing this message Instance".printBikeName()
}
